[build]
  functions = "functions"  # Point to the 'functions' folder for serverless functions
  publish = "static"       # Static assets are in the 'static' folder

[[redirects]]
  from = "/merge-pdfs"
  to = "/functions/app.py"  # Route the '/merge-pdfs' to the app.py function
  status = 200
