[build]
  functions = "functions"  # Directory where your Flask app's serverless functions are located
  publish = "static"       # Directory for static files (CSS, JS, images)

[[redirects]]
  from = "/merge-pdfs"
  to = "/functions/handler.py"
  status = 200
